### ISSUE TITLE
Download email text

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#129]
Downloads email:

"Also cite the contributing data providers which are listed in the included "citation.csv" file. More information can be found at citing the ALA. "

citing the ALA link to go directly to:https://support.ala.org.au/support/solutions/articles/6000195866-how-to-cite-the-ala rather than the current redirect from https://www.ala.org.au/about-the-atlas/terms-of-use/citing-the-atlas/

re format date:

format the date (currently 'Mon Jul 27 16:24:29 AEST 2020') to '27 July 2020'? This is the format that's used across all citation examples: 'xxx. Accessed 28 January 2020.’

**Comment by alexhuang091** [comment]
2 PRS waiting for approval for this change:
https://github.com/AtlasOfLivingAustralia/ala-install/pull/415
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/510

**Comment by ansell** [comment]
@M-Nicholls There are distinct advantages to having a redirect that we control, going through www.ala.org.au for maintainability over time. What advantages are there in using a direct link to the current support article (whose URL we do not control due to the use of an internal freshdesk ID as part of it and is prone to changes over time).

**Comment by M-Nicholls** [comment]
the date is using an abbreviated month (e.g. Aug)- can we use the full month e.g. When using this dataset please use the following citation: 
Atlas of Living Australia occurrence download at https://doi-test.ala.org.au/doi/10.80416/TEST_DOI_5f3c5b442f044 accessed on 19 August 2020.
