### ISSUE TITLE
Additional metadata entries - update messages.properties

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#142]
user_assertions
year
duplicate_record
license

update messages.properties with wiki link and description

while editing the file update 

description.outlier_layer_count=The number of environmental spatial layers for which this record has been identified as an outlier by the Reverse Jackknife method

Currently has "envinonmental"

**Comment by alexhuang091** [comment]
Hi Miles, I think the result to achieve is updated description and wiki for those fields. so

<img width="581" alt="Screen Shot 2020-09-30 at 12 39 50 pm" src="https://user-images.githubusercontent.com/61677987/94642358-3acc2f80-0327-11eb-8802-8c5e5f091f1c.png"> 

changed to 

<img width="585" alt="Screen Shot 2020-09-30 at 2 17 50 pm" src="https://user-images.githubusercontent.com/61677987/94642558-d067bf00-0327-11eb-9bac-7c28346bd6ed.png">

This is easy because the 'Description' in the table comes from `facet.user_assertions`, we can directly change it.

<img width="1005" alt="Screen Shot 2020-09-30 at 2 14 58 pm" src="https://user-images.githubusercontent.com/61677987/94642451-79fa8080-0327-11eb-91b5-4979a2e2237e.png">

But it has a side effect, `facet.user_assertions` is used by biocache-service to translate the fq

so
<img width="385" alt="Screen Shot 2020-09-30 at 2 24 21 pm" src="https://user-images.githubusercontent.com/61677987/94642839-b24e8e80-0328-11eb-80cf-8bece41120bb.png">

changed to 

<img width="919" alt="Screen Shot 2020-09-30 at 2 10 09 pm" src="https://user-images.githubusercontent.com/61677987/94642498-9b5b6c80-0327-11eb-9db6-34de3fa71d90.png">

I think this is not what we want.

**Comment by alexhuang091** [comment]
We call the /ws/index/fields API to get the fields info, the result is like this

<img width="1384" alt="Screen Shot 2020-09-30 at 2 28 24 pm" src="https://user-images.githubusercontent.com/61677987/94643070-52a4b300-0329-11eb-95f0-e606823f3604.png">

There is an **info** field we can put the new description into. Actually, description.xxx in the properties will be set into the info field in the JSON result.

![image](https://user-images.githubusercontent.com/61677987/94643799-f5a9fc80-032a-11eb-9c64-b720af065e59.png)

Actually, the path (from property file to ala-hub popup) is like this.

```
In property file              In JSON result               In Ala-hub popup

facet.xxx           ---->    description field         -->  shown in description column.
description.xxx.    ---->    info field
```

So in ala-hub, instead of showing the description field of the result (which comes from facet.xxx in the properties file which in last comment I said we can' change), we can put all the new/updated descriptions in this task into the description.xxx and show the info field in the 'Description' column of the table.

**Comment by alexhuang091** [comment]
But there's also an issue with this approach. Biocache service appends DWC term at the end of info. Like this

![image](https://user-images.githubusercontent.com/61677987/94644458-b4b2e780-032c-11eb-9278-24e89af58d94.png)
 
If you are ok with the appended dwc link. I'll go with this approach.

**Comment by M-Nicholls** [comment]
I think we'd be ok with the appended DwC link so let's go with that

**Comment by nickdos** [comment]
@alexhuang091 can you pls QA this - assuming its deployed to biocache-dq-test?

**Comment by alexhuang091** [comment]
> @alexhuang091 can you pls QA this - assuming its deployed to biocache-dq-test?

Hi Nick, biocache-dq-test is not reachable right now, the same version is deployed onto biocache-dq-beta and it has all the changes.

**Comment by nickdos** [comment]
Thanks @alexhuang091 - I'll take that as having passed your QA and move this issue into "Ready for CAB".
