### ISSUE TITLE
Update filter group labels to be consistent and informative

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#151]
Difference between exclude (most of them) and include (just the post 1700) filters
Thought filter labels were not informative. E.g. Location, Spatially suspect and location uncertainty could all be confused; "user assertion" is not obvious to new user - possible call "user annotation" or "user flagged".

**Comment by RobinaSanderson** [comment]
Hi @M-Nicholls - I would include the geospatial kosher flag in with the rest of the location quality issues as "spatially suspect" and  low location quality mean the same thing to me.

I would probably use "spatially suspect" for the  all the location quality issues because I interpret that label as saying, "the ALA suspects there is an issue with the geographical coordinates that have been given". Which is different to the spatial uncertainty value provided by the data provider. Does that make sense?

Minor quibble, could change "...with user annotations" to "...with unresolved user annotations"

Happy to talk about it if you want to call. Realise not having even numbers of categories for location categories and everything else might make it more difficult to order. I remember Nick having another suggestion about the wording in the little bit of the review I got to, but I can't remember the detail, sorry.

**Comment by M-Nicholls** [comment]
move spatially suspect to the top
change to Exclude records with additional location quality issues
