### ISSUE TITLE
Filter data on location

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#31]
**User Story:**

As a: Data User
I want: Default results filtered on location
So that: Locations are accurate to a threshold

**Acceptance Criteria:**

Given: I am on the ALA website and have queried 
When: My results are returned
Then:
the data is pre filtered on
exclude “spatially suspect”
&fq=-geospatial_kosher%3A%22false%22
Habitat match – terrestrial points in the sea - in the assertions query
fq=-(assertions%3AhabitatMismatch)
Coordinate uncertainty is less than 10km
&fq=coordinate_uncertainty%3A[%220%22%20TO%20%2210000%22]

**Comment by ansell** [comment]
The `coordinate_uncertainty` filter is overly broad at this point because we have never told our data providers that the field was mandatory, so its coverage is scattered across the ALA. 

**WARNING: There are a few hundred data resources that will be completely removed from the default view of the ALA if it is included in its current form.**

**Comment by alexhuang091** [comment]
`coordinate_uncertainty` can also be a negative value, there're 102472 records have `coordinate_uncertainty` in the range [-10000, 0]

**Comment by ansell** [comment]
Can you change the filter to only remove negative `coordinate_uncertainty` values instead of excluding records that do not have any value for `coordinate_uncertainty`? 

When Miles was Data Manager we were never given advice that this field would be mandatory in the future, so there are large number of data resources that do not have this field at all and are being excluded completely in the current version of the filter.

**Comment by M-Nicholls** [comment]
Thanks Peter, one thing I needed when setting up the filters is to get the user community involved in setting the fields and thresholds.  So the location filter has been set like this during testing to deliberately provoke discussion.  I'd say it's unlikely to make it to production with the settings as they are but if it does we'll make sure there is substantial communications accompanying it and enough time for people to revise their data if needed.

**Comment by M-Nicholls** [comment]
I've modified the fq used to filter out only records where there is a coordinate uncertainty and it's over 10k

-coordinate_uncertainty:[10000 TO *]

**Comment by RobinaSanderson** [comment]
Recreated in test as:
![image](https://user-images.githubusercontent.com/23368496/87623050-d659f500-c767-11ea-98e9-169bfe74f0d0.png)
