### ISSUE TITLE
See what data filters have been applied

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#37]
**User Story:**

As a: Data User
I want: to see the filters what are applied by default - including the number of records impacted 
So that: I understand what records have been excluded

**Acceptance Criteria:**

Given: I am on the ALA website and have queried 
When: I view the results of my query
Then:
The list of applied filters is clearly visible at the top of the search results
filters are expandable categories, initially collapsed
assertions (records excluded count)
location (records excluded count)
identification (records excluded count)
event (records excluded count)
duplicates (records excluded count)
outliers (records excluded count)
user assertions (records excluded count)

**Comment by M-Nicholls** [comment]
separate UI element to the use selected filters
show that DQ filter is applied
it's a pre-filter
link or mouse over to describe what the filter is
text description stored in the config DB

**Comment by ansell** [comment]
All of the collections.ala.org.au links through to biocache for records affected by the `coordinate_uncertainty` broad filter show up as effectively error pages (no records returned from the query) with no opportunity for the user to know that the data quality filters are hiding the entire data resource for them currently. 

The `biocache-hubs` "no records" error page must indicate clearly that the filters are active and allow the user to immediately override or disable them before the filters will be less harmful to users than they are useful.

Eg, this collection is completely hidden currently because of the coordinate_uncertainty filter and there is no opportunity on the page to do anything further.

https://collections.ala.org.au/public/showDataResource/dr10487

https://biocache-dq-test.ala.org.au/occurrences/search?q=data_resource_uid%3A%22dr10487%22

**Note the complete lack of references to filters on the error page, which would be destructive to the ALA reputation if it were deployed in its current form to production:**

<img width="1320" alt="Screen Shot 2020-03-31 at 6 40 01 am" src="https://user-images.githubusercontent.com/82365/77954552-7fe0bc00-731a-11ea-8794-2a866056b75b.png">

**Comment by M-Nicholls** [comment]
when goes to production we need to test the links from collectory pages

**Comment by ansell** [comment]
Downloading the data_resource_uid facet list from biocache with no filters enabled and comparing it to the data_resource_uid facet list with all of the filters enabled would identify the collectory links to be tested.

The pattern with all of the filters enabled is the following:

`https://biocache-dq-test.ala.org.au/occurrences/facets/download?q=*%3A*&facets=data_resource_uid`

Unfortunately each of the filters must be disabled with a new parameter in the current implementation, so the URL grows substantially when removing each filter in turn (and if new categories are added they will need to be added to this URL for the test plan):

`https://biocache-dq-test.ala.org.au/occurrences/facets/download?q=*%3A*&disableQualityFilter=location&disableQualityFilter=taxon-identification&disableQualityFilter=outliers&disableQualityFilter=duplicate&disableQualityFilter=user-assertions&disableQualityFilter=dates&facets=data_resource_uid`

One thing to note with the current version of the UX is that it isn't colour-blind friendly currently. There is red text that operates as a button with no border around it, so it doesn't standout to me and possibly other Red-deficient colour-blind users. I didn't realise that "ON" was a clickable button until I used the Filters interface to disable one and it changed to "OFF":

<img width="1079" alt="Screen Shot 2020-04-08 at 2 22 32 pm" src="https://user-images.githubusercontent.com/82365/78744234-6982d200-79a4-11ea-8bae-2b31fd1aaf79.png">
