### ISSUE TITLE
manage interaction with user filters and DQ filters

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#60]
If a user filters on a field where a DQ filter is already applied the DQ filter is switched off and the user filter is applied

how are facets displayed where a DQ filter is applied e.g. if 1900 -> then the facet doesn't show pre 1900?

filters applied for a session - do the filter need to persist between sessions

clearly indicate to the user what's happened

**Comment by alexhuang091** [comment]
Currently for each category admin can add more than one filter. For example, location has  
* geospatial_kosher:"false"
* -assertions:habitatMismatch
* coordinate_uncertainty:["0" TO "10000"]
so we construct a **fq=geospatial_kosher:"false" AND -assertions:habitatMismatch coordinate_uncertainty:["0" TO "10000"]**

so the question is do we look for an exact match ? (user species fq=xxx AND xxx AND xxx) or as long as user specifies fq=geospatial_kosher:xxx or fq=assertions:xxx or fq=coordinate_uncertainty:xxx

**Comment by sbearcsiro** [comment]
Currently, facet values that are excluded by the data quality filters will not be shown to the user.  ie the date quality filters will exclude records before 1900 therefore the decade facet will not show any of decades before 1900

Since facet values only include the values included in the search results, instead of "switching off" data quality filter parts to match the user's filter queries, we give the user the option to break the data quality filter out into user filters of the combined parts.  This gives the user the ability to elect to remove a filter that was preventing them from accessing facet values they're interested in.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/biocache-hubs/review/BH-CR-16

**Comment by M-Nicholls** [comment]
https://biocache-dq-test.ala.org.au/occurrences/search?q=*%3A*&fq=-%28geospatial_kosher%3A%22false%22%29&fq=-%28assertions%3A%22habitatMismatch%22%29&fq=coordinate_uncertainty%3A%5B0+TO+20000%5D

the red highlight is good and the mouse over text on the "user selected filter" is good, can we add the same text to the mouse over on the "Quality filters applied" section indicating the user filter that is affecting the DQ filter and provide the details of the filter being affected e.g. This filter may conflict with these default quality filters:[location, coordinate uncertainty (in metres): [0 TO 10000]

**Comment by M-Nicholls** [comment]
Looks great - some UI elements to be modified as indicated in https://github.com/AtlasOfLivingAustralia/DataQuality/issues/73
