### ISSUE TITLE
use DQ filters via API

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#74]
make the DQ filters as set in the Admin available via an API so that they can be used in other ALA components -e.g. the regions app or spatial portal

talk to systems team when designing

**Comment by sbearcsiro** [comment]
This change has two options for the DQ filters API:
1. As a map via /dataQuality/list
2. As a list via /dataQuality/list?flatten=true

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/biocache-hubs/review/BH-CR-19

**Comment by nickdos** [comment]
Output looks good. Only comment I have is that it would be good to provide an` i18nCode` value in addition to the `title`, so that LA hubs can provide translations in the UI. The `/occurrences/search` service has this for the `facets` output. 

Not sure how to generate the code though... was thinking it could just be the `title` munged to convert spaces to underscores but then the client code could also just do this instead. 

@djtfmartin any ideas on i18n aspect for this service... is it needed?
