### ISSUE TITLE
additional information on DQ filters

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/DataQuality#84]
tool tips on values

particularly the assertions

where to get the information from?

**Comment by alexhuang091** [comment]
Hi Miles, you mean tooltips for values like : nameNotRecognised, invalidScientificName?

The thing is, while backend can correctly translate when there's one key/value pair in fq, 
for example `fq=-assertions:"nameNotRecognised"` or `fq=-assertions:"invalidScientificName"`

<img width="480" alt="Screen Shot 2020-05-06 at 12 00 53 pm" src="https://user-images.githubusercontent.com/61677987/81132301-43475680-8f91-11ea-9c5e-39fc99031fbf.png">
<img width="429" alt="Screen Shot 2020-05-06 at 11 54 11 am" src="https://user-images.githubusercontent.com/61677987/81132313-4b06fb00-8f91-11ea-8e87-07d5ab184d86.png">

but when we combine them into one fq: `fq=-assertions:"nameNotRecognised"  AND -assertions:"invalidScientificName"`(because they are in same category), backend failed to translate it.

<img width="619" alt="Screen Shot 2020-05-06 at 12 04 09 pm" src="https://user-images.githubusercontent.com/61677987/81132429-c072cb80-8f91-11ea-872f-1e81cafa26f4.png">

but actually -key1:value1 AND -key2:value2 logically equals to -(key1:value1 OR key2:value2)
so if I change the above fq to `fq=-(assertions:"nameNotRecognised" OR assertions:"invalidScientificName")`, it's correctly translated

<img width="645" alt="Screen Shot 2020-05-06 at 12 09 36 pm" src="https://user-images.githubusercontent.com/61677987/81132664-940b7f00-8f92-11ea-8662-757ebe807412.png">


so biocache-service needs changes to accept our `fq=-assertions:"nameNotRecognised" AND -assertions:"invalidScientificName" AND xxxx` or we can investigate if we can create an API which accepts a value and return a translated, meaningful value.

**Comment by M-Nicholls** [comment]
in the User Assertions quality filters dialogue

Filter applied: fq=-user_assertions:50005 AND -user_assertions:50001

Filter applied: exclude user_assertions: unconfirmed AND exclude user_assertions: open issue

field list table is good

**Comment by alexhuang091** [comment]
in current production ala, if you add &fq=-user_assertions:50005 AND -user_assertions:50001 to url then it can't be properly translated, I mean you still see '50005' and '50001'.

I'll check biocache-service side.

<img width="937" alt="Screen Shot 2020-05-06 at 1 02 23 pm" src="https://user-images.githubusercontent.com/61677987/81134998-e43a0f80-8f99-11ea-9784-938e6c03006e.png">

**Comment by M-Nicholls** [comment]
the user_assertions vocab values are looked up in the biocache service
find out where the vocab values are looked up and populate something similar for the assertions
